name: books
description: An app displaying list of books using the Google books API.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: "2.14.0 "

dependencies:
  flutter:
    sdk: flutter

  google_fonts: 2.1.0

  hooks_riverpod: 0.14.0+5
  flutter_hooks: 0.18.0

  firebase_core: 1.7.0
  firebase_auth: 3.1.3
  cloud_firestore: 2.5.3
  cloud_functions: 3.0.4
  google_sign_in: 5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  logging: 1.0.2
  mocktail: 0.2.0

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: 1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
